const ResponseCode = {
  SUCCESS: 'SUCCESS',
  CREATED: 'CREATED',
  BAD_REQUEST: 'BAD_REQUEST',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR'
};

const ResponseMessage = {
  // Auth
  REGISTER_SUCCESS: ResponseMessage.REGISTER_SUCCESS,
  LOGIN_SUCCESS: ResponseMessage.LOGIN_SUCCESS,
  PROFILE_RETRIEVED: ResponseMessage.PROFILE_RETRIEVED,
  EMAIL_IN_USE: ResponseMessage.EMAIL_IN_USE,
  INVALID_CREDENTIALS: ResponseMessage.INVALID_CREDENTIALS,
  
  // User
  USERS_RETRIEVED: ResponseMessage.USERS_RETRIEVED,
  USER_RETRIEVED: ResponseMessage.USER_RETRIEVED,
  USER_NOT_FOUND: ResponseMessage.USER_NOT_FOUND,

  // Booking
  BOOKING_CREATED: ResponseMessage.BOOKING_CREATED,
  MY_BOOKINGS_RETRIEVED: ResponseMessage.MY_BOOKINGS_RETRIEVED,
  ALL_BOOKINGS_RETRIEVED: ResponseMessage.ALL_BOOKINGS_RETRIEVED,
  BOOKING_RETRIEVED: ResponseMessage.BOOKING_RETRIEVED,
  BOOKING_APPROVED: ResponseMessage.BOOKING_APPROVED,
  BOOKING_REJECTED: ResponseMessage.BOOKING_REJECTED,
  BOOKING_NOT_FOUND: ResponseMessage.BOOKING_NOT_FOUND,
  NO_PERMISSION_BOOKING: ResponseMessage.NO_PERMISSION_BOOKING,
  CONFLICT_BOOKING: ResponseMessage.CONFLICT_BOOKING,
  CONFLICT_APPROVE: ResponseMessage.CONFLICT_APPROVE,
  END_TIME_ERROR: ResponseMessage.END_TIME_ERROR,

  // Field
  FIELDS_RETRIEVED: ResponseMessage.FIELDS_RETRIEVED,
  FIELD_RETRIEVED: ResponseMessage.FIELD_RETRIEVED,
  FIELD_CREATED: ResponseMessage.FIELD_CREATED,
  FIELD_UPDATED: ResponseMessage.FIELD_UPDATED,
  FIELD_DELETED: ResponseMessage.FIELD_DELETED,
  FIELD_NOT_FOUND: ResponseMessage.FIELD_NOT_FOUND,
  FIELD_NOT_ACTIVE: ResponseMessage.FIELD_NOT_ACTIVE,

  // Payment
  PAYMENT_SUBMITTED: ResponseMessage.PAYMENT_SUBMITTED,
  PAYMENTS_RETRIEVED: ResponseMessage.PAYMENTS_RETRIEVED,
  PAYMENT_VERIFIED: ResponseMessage.PAYMENT_VERIFIED,
  PAYMENT_REJECTED: ResponseMessage.PAYMENT_REJECTED,
  PAYMENT_NOT_FOUND: ResponseMessage.PAYMENT_NOT_FOUND,
  PAY_OWN_BOOKING: ResponseMessage.PAY_OWN_BOOKING,
  PAYMENT_EXISTS: ResponseMessage.PAYMENT_EXISTS,

  // Middleware / Generic
  UNAUTHORIZED: ResponseMessage.UNAUTHORIZED,
  TOKEN_USER_DELETED: ResponseMessage.TOKEN_USER_DELETED,
  TOKEN_INVALID: ResponseMessage.TOKEN_INVALID,
  FORBIDDEN: ResponseMessage.FORBIDDEN,
  NOT_FOUND_ENDPOINT: ResponseMessage.NOT_FOUND_ENDPOINT,
};

module.exports = {
  ResponseCode,
  ResponseMessage
};
